version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3001:3001'
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '8080:80'
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
