# Imagem base Node
FROM node:18

# Define diretório de trabalho
WORKDIR /app

# Copia pacotes e instala dependências
COPY package*.json ./
RUN npm install

# Copia o restante da aplicação
COPY . .

# Expõe a porta do Express
EXPOSE 3001

# Comando de inicialização
CMD ["node", "src/index.js"]
